/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SoftwaresRouteImport } from './routes/softwares'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminDownloadsRouteImport } from './routes/admin/downloads'
import { Route as AdminSoftwareCategoriesRouteImport } from './routes/admin/software-categories'
import { Route as AdminSoftwaresRouteImport } from './routes/admin/softwares'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwaresRoute = SoftwaresRouteImport.update({
  id: '/softwares',
  path: '/softwares',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/admin/downloads',
  path: '/admin/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSoftwareCategoriesRoute = AdminSoftwareCategoriesRouteImport.update({
  id: '/admin/software-categories',
  path: '/admin/software-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSoftwaresRoute = AdminSoftwaresRouteImport.update({
  id: '/admin/softwares',
  path: '/admin/softwares',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/softwares': typeof SoftwaresRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/software-categories': typeof AdminSoftwareCategoriesRoute
  '/admin/softwares': typeof AdminSoftwaresRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/softwares': typeof SoftwaresRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/software-categories': typeof AdminSoftwareCategoriesRoute
  '/admin/softwares': typeof AdminSoftwaresRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/softwares': typeof SoftwaresRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/software-categories': typeof AdminSoftwareCategoriesRoute
  '/admin/softwares': typeof AdminSoftwaresRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/softwares'
    | '/admin/courses'
    | '/admin/downloads'
    | '/admin/software-categories'
    | '/admin/softwares'
    | '/auth/confirm'
    | '/courses/$courseId'
    | '/admin/'
    | '/courses/'
    | '/api/public/mercadopago-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/softwares'
    | '/admin/courses'
    | '/admin/downloads'
    | '/admin/software-categories'
    | '/admin/softwares'
    | '/auth/confirm'
    | '/courses/$courseId'
    | '/admin'
    | '/courses'
    | '/api/public/mercadopago-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/softwares'
    | '/admin/courses'
    | '/admin/downloads'
    | '/admin/software-categories'
    | '/admin/softwares'
    | '/auth/confirm'
    | '/courses/$courseId'
    | '/admin/'
    | '/courses/'
    | '/api/public/mercadopago-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SoftwaresRoute: typeof SoftwaresRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminSoftwareCategoriesRoute: typeof AdminSoftwareCategoriesRoute
  AdminSoftwaresRoute: typeof AdminSoftwaresRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/softwares': {
      id: '/softwares'
      path: '/softwares'
      fullPath: '/softwares'
      preLoaderRoute: typeof SoftwaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/admin/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/software-categories': {
      id: '/admin/software-categories'
      path: '/admin/software-categories'
      fullPath: '/admin/software-categories'
      preLoaderRoute: typeof AdminSoftwareCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/softwares': {
      id: '/admin/softwares'
      path: '/admin/softwares'
      fullPath: '/admin/softwares'
      preLoaderRoute: typeof AdminSoftwaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthConfirmRoute: typeof AuthConfirmRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmRoute: AuthConfirmRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SoftwaresRoute: SoftwaresRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminSoftwareCategoriesRoute: AdminSoftwareCategoriesRoute,
  AdminSoftwaresRoute: AdminSoftwaresRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
