/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as SoftwaresRouteImport } from './routes/softwares'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminDownloadsRouteImport } from './routes/admin/downloads'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminSoftwareCategoriesRouteImport } from './routes/admin/software-categories'
import { Route as AdminSoftwaresRouteImport } from './routes/admin/softwares'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as SoftwaresIndexRouteImport } from './routes/softwares.index'
import { Route as SoftwaresSoftwareIdRouteImport } from './routes/softwares.$softwareId'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwaresRoute = SoftwaresRouteImport.update({
  id: '/softwares',
  path: '/softwares',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoftwareCategoriesRoute = AdminSoftwareCategoriesRouteImport.update({
  id: '/software-categories',
  path: '/software-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoftwaresRoute = AdminSoftwaresRouteImport.update({
  id: '/softwares',
  path: '/softwares',
  getParentRoute: () => AdminRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwaresIndexRoute = SoftwaresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SoftwaresRoute,
} as any)
const SoftwaresSoftwareIdRoute = SoftwaresSoftwareIdRouteImport.update({
  id: '/$softwareId',
  path: '/$softwareId',
  getParentRoute: () => SoftwaresRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contato': typeof ContatoRoute
  '/softwares': typeof SoftwaresRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/software-categories': typeof AdminSoftwareCategoriesRoute
  '/admin/softwares': typeof AdminSoftwaresRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/softwares/$softwareId': typeof SoftwaresSoftwareIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/softwares/': typeof SoftwaresIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/contato': typeof ContatoRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/software-categories': typeof AdminSoftwareCategoriesRoute
  '/admin/softwares': typeof AdminSoftwaresRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/softwares/$softwareId': typeof SoftwaresSoftwareIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/softwares': typeof SoftwaresIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contato': typeof ContatoRoute
  '/softwares': typeof SoftwaresRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/software-categories': typeof AdminSoftwareCategoriesRoute
  '/admin/softwares': typeof AdminSoftwaresRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/softwares/$softwareId': typeof SoftwaresSoftwareIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/softwares/': typeof SoftwaresIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contato'
    | '/softwares'
    | '/admin/courses'
    | '/admin/downloads'
    | '/admin/messages'
    | '/admin/sales'
    | '/admin/software-categories'
    | '/admin/softwares'
    | '/auth/confirm'
    | '/courses/$courseId'
    | '/softwares/$softwareId'
    | '/admin/'
    | '/courses/'
    | '/softwares/'
    | '/api/public/mercadopago-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/admin/courses'
    | '/admin/downloads'
    | '/admin/messages'
    | '/admin/sales'
    | '/admin/software-categories'
    | '/admin/softwares'
    | '/auth/confirm'
    | '/courses/$courseId'
    | '/softwares/$softwareId'
    | '/admin'
    | '/courses'
    | '/softwares'
    | '/api/public/mercadopago-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contato'
    | '/softwares'
    | '/admin/courses'
    | '/admin/downloads'
    | '/admin/messages'
    | '/admin/sales'
    | '/admin/software-categories'
    | '/admin/softwares'
    | '/auth/confirm'
    | '/courses/$courseId'
    | '/softwares/$softwareId'
    | '/admin/'
    | '/courses/'
    | '/softwares/'
    | '/api/public/mercadopago-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  SoftwaresRoute: typeof SoftwaresRouteWithChildren
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/softwares': {
      id: '/softwares'
      path: '/softwares'
      fullPath: '/softwares'
      preLoaderRoute: typeof SoftwaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/software-categories': {
      id: '/admin/software-categories'
      path: '/software-categories'
      fullPath: '/admin/software-categories'
      preLoaderRoute: typeof AdminSoftwareCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/softwares': {
      id: '/admin/softwares'
      path: '/softwares'
      fullPath: '/admin/softwares'
      preLoaderRoute: typeof AdminSoftwaresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/softwares/': {
      id: '/softwares/'
      path: '/'
      fullPath: '/softwares/'
      preLoaderRoute: typeof SoftwaresIndexRouteImport
      parentRoute: typeof SoftwaresRoute
    }
    '/softwares/$softwareId': {
      id: '/softwares/$softwareId'
      path: '/$softwareId'
      fullPath: '/softwares/$softwareId'
      preLoaderRoute: typeof SoftwaresSoftwareIdRouteImport
      parentRoute: typeof SoftwaresRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSoftwareCategoriesRoute: typeof AdminSoftwareCategoriesRoute
  AdminSoftwaresRoute: typeof AdminSoftwaresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSoftwareCategoriesRoute: AdminSoftwareCategoriesRoute,
  AdminSoftwaresRoute: AdminSoftwaresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthConfirmRoute: typeof AuthConfirmRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmRoute: AuthConfirmRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SoftwaresRouteChildren {
  SoftwaresSoftwareIdRoute: typeof SoftwaresSoftwareIdRoute
  SoftwaresIndexRoute: typeof SoftwaresIndexRoute
}

const SoftwaresRouteChildren: SoftwaresRouteChildren = {
  SoftwaresSoftwareIdRoute: SoftwaresSoftwareIdRoute,
  SoftwaresIndexRoute: SoftwaresIndexRoute,
}

const SoftwaresRouteWithChildren = SoftwaresRoute._addFileChildren(
  SoftwaresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContatoRoute: ContatoRoute,
  SoftwaresRoute: SoftwaresRouteWithChildren,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
